/*
389. Find the Difference
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.
*/

class Solution {
public:
    char findTheDifference(std::string s, std::string t) 
    {
        std::unordered_map<char,int> um{};
        for (char c : s) um[c]++;

        for(char c : t)
        {
            if (um[c] == 0) return c;
            um[c]--;
        }

        return ' ';
    }
};
